"""
rule_dictionary.py
Case-level Hebbian rule accumulation for NEXUS.

Biological analogy:
  Individual case → micro-rule         =  CA3 rapid encoding (single episode)
  Rule count crosses threshold         =  Sharp-wave ripple (SWR) trigger
  LLM consolidates rule → principle    =  Neocortical consolidation

Compared to the node-level refine loop (expensive 300-case probe per change),
micro-rules are:
  - Generated on every misclassification (zero LLM cost for accumulation)
  - Validated by repetition, not by a separate probe
  - Consolidated only when evidence is sufficient (threshold gate)

Usage:
    rd = RuleDictionary(threshold=5, path="run/rule_dict.json")
    fired = rd.add(MicroRule(...))
    if fired:
        principle = rd.consolidate(key, llm_fn)   # expensive, rare
        principles_store.add_principle(...)
    rd.save()
"""

from __future__ import annotations

import json
import re
import threading
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Callable


# ─── Data structures ──────────────────────────────────────────────────────────

@dataclass
class MicroRule:
    """A candidate rule generated from a single misclassified case."""
    pattern: str          # The linguistic/clinical pattern observed
    signal: str           # "ADE" or "NOT_ADE"
    confidence: float     # 0.0–1.0 from the LLM that generated it
    context: str          # the original sentence (for deduplication + examples)
    node_id: str          # which node misclassified this case
    round_num: int        # which training round


@dataclass
class RuleEntry:
    """Accumulated evidence for a single pattern."""
    pattern: str
    signal: str           # "ADE" or "NOT_ADE"
    count: int = 0        # Hebbian accumulation (LTP)
    strength: float = 0.0 # sum of confidence scores
    contexts: list[str] = field(default_factory=list)
    node_ids: list[str] = field(default_factory=list)
    promoted: bool = False
    promoted_round: int = -1
    principle_id: str = ""

    @property
    def avg_confidence(self) -> float:
        return self.strength / max(1, self.count)

    def to_dict(self) -> dict:
        return asdict(self)

    @staticmethod
    def from_dict(d: dict) -> "RuleEntry":
        e = RuleEntry(**{k: v for k, v in d.items()})
        return e


# ─── RuleDictionary ───────────────────────────────────────────────────────────

class RuleDictionary:
    """
    Thread-safe accumulator for micro-rules generated by parallel MicroLearners.

    Each call to .add() performs Hebbian LTP on the matching rule entry.
    When a rule's count crosses `threshold`, the entry fires — a consolidation
    event that should prompt an LLM to formalize it as a NEXUS principle.

    Pruning: rules that accumulate slowly over many rounds have their strength
    decayed (LTD) to prevent stale patterns from eventually crossing threshold.
    """

    def __init__(
        self,
        threshold: int = 5,
        max_contexts: int = 8,
        ltd_decay: float = 0.05,   # applied per round to non-firing rules
        path: str | None = None,
    ):
        self.threshold = threshold
        self.max_contexts = max_contexts
        self.ltd_decay = ltd_decay
        self.path = Path(path) if path else None

        self._rules: dict[str, RuleEntry] = {}
        self._lock = threading.Lock()
        self._fired_this_round: list[str] = []  # keys that crossed threshold

    # ── Normalisation ─────────────────────────────────────────────────────────

    @staticmethod
    def _normalize(pattern: str) -> str:
        """Collapse whitespace and lowercase for deduplication."""
        return re.sub(r"\s+", " ", pattern.strip().lower())

    # ── Core Hebbian update ───────────────────────────────────────────────────

    def add(self, rule: MicroRule) -> bool:
        """
        Add a micro-rule observation (LTP).
        Returns True if this addition crosses the engram threshold (SWR event).
        Thread-safe.
        """
        key = self._normalize(rule.pattern)
        fired = False

        with self._lock:
            if key not in self._rules:
                self._rules[key] = RuleEntry(pattern=rule.pattern, signal=rule.signal)

            entry = self._rules[key]
            if entry.promoted:
                return False  # already consolidated — don't fire again

            prev_count = entry.count
            entry.count += 1
            entry.strength += rule.confidence

            # Keep a capped sample of contexts for later consolidation
            if len(entry.contexts) < self.max_contexts:
                entry.contexts.append(rule.context[:300])
            if rule.node_id not in entry.node_ids:
                entry.node_ids.append(rule.node_id)

            # Threshold crossing (LTP → engram)
            if prev_count < self.threshold <= entry.count:
                self._fired_this_round.append(key)
                fired = True

        return fired

    # ── LTD (decay) ──────────────────────────────────────────────────────────

    def apply_ltd(self, current_round: int) -> int:
        """
        Apply long-term depression to rules that haven't fired.
        Call once per round. Returns number of rules pruned.
        """
        pruned = 0
        with self._lock:
            dead_keys = []
            for key, entry in self._rules.items():
                if entry.promoted:
                    continue
                entry.strength = max(0.0, entry.strength - self.ltd_decay * entry.count)
                # Prune if strength collapsed below 0.5 and count is low
                if entry.strength < 0.5 and entry.count < 2:
                    dead_keys.append(key)
            for k in dead_keys:
                del self._rules[k]
                pruned += 1
        return pruned

    # ── Consolidation ─────────────────────────────────────────────────────────

    def pop_fired(self) -> list[str]:
        """Return and clear the list of keys that fired this round."""
        with self._lock:
            fired = list(self._fired_this_round)
            self._fired_this_round.clear()
        return fired

    def get_entry(self, key: str) -> RuleEntry | None:
        return self._rules.get(key)

    def mark_promoted(self, key: str, principle_id: str, round_num: int):
        """Mark a rule as consolidated — prevents future re-firing."""
        with self._lock:
            if key in self._rules:
                self._rules[key].promoted = True
                self._rules[key].principle_id = principle_id
                self._rules[key].promoted_round = round_num

    def build_consolidation_prompt(self, key: str) -> str:
        """
        Build the LLM prompt that formalizes a threshold-crossing rule
        into a NEXUS principle. Called once per SWR event.
        """
        entry = self._rules.get(key)
        if not entry:
            return ""

        examples = "\n".join(
            f"  [{i+1}] {ctx}" for i, ctx in enumerate(entry.contexts[:6])
        )
        return f"""You are NEXUS, a clinical pharmacovigilance classifier.

A recurring pattern has been observed across {entry.count} misclassified cases.
Each time this pattern appeared, the correct answer was {entry.signal}.

Pattern: "{entry.pattern}"
Average LLM confidence: {entry.avg_confidence:.2f}
Nodes where errors occurred: {', '.join(entry.node_ids)}

Example sentences where this pattern appeared:
{examples}

Task: Write a concise, actionable NEXUS principle (2–4 sentences) that:
1. States when this pattern reliably signals {entry.signal}
2. Explains the clinical reasoning
3. Identifies any exceptions or caveats

Begin with "NEXUS PRINCIPLE:" and write in present tense.
Do not repeat the examples verbatim."""

    # ── Persistence ──────────────────────────────────────────────────────────

    def save(self):
        if not self.path:
            return
        with self._lock:
            data = {
                "threshold": self.threshold,
                "ltd_decay": self.ltd_decay,
                "rules": {k: v.to_dict() for k, v in self._rules.items()},
            }
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(data, indent=2))

    @classmethod
    def load(cls, path: str, **kwargs) -> "RuleDictionary":
        p = Path(path)
        if not p.exists():
            return cls(path=path, **kwargs)
        data = json.loads(p.read_text())
        rd = cls(
            threshold=data.get("threshold", 5),
            ltd_decay=data.get("ltd_decay", 0.05),
            path=path,
        )
        for key, d in data.get("rules", {}).items():
            rd._rules[key] = RuleEntry.from_dict(d)
        return rd

    # ── Reporting ─────────────────────────────────────────────────────────────

    def summary_stats(self) -> dict:
        with self._lock:
            total = len(self._rules)
            promoted = sum(1 for e in self._rules.values() if e.promoted)
            near_threshold = sum(
                1 for e in self._rules.values()
                if not e.promoted and e.count >= self.threshold - 1
            )
            top = sorted(
                [e for e in self._rules.values() if not e.promoted],
                key=lambda e: e.count, reverse=True
            )[:5]
        return {
            "total_rules": total,
            "promoted": promoted,
            "near_threshold": near_threshold,
            "threshold": self.threshold,
            "top_accumulating": [
                {"pattern": e.pattern[:60], "count": e.count,
                 "signal": e.signal, "avg_conf": round(e.avg_confidence, 2)}
                for e in top
            ],
        }

    def print_report(self):
        stats = self.summary_stats()
        print(f"\n[RuleDict] {stats['total_rules']} rules "
              f"| {stats['promoted']} promoted "
              f"| {stats['near_threshold']} near threshold ({self.threshold})")
        if stats["top_accumulating"]:
            print("[RuleDict] Top accumulating rules:")
            for r in stats["top_accumulating"]:
                bar = "█" * r["count"] + "░" * max(0, self.threshold - r["count"])
                print(f"  [{bar}] x{r['count']} {r['signal']:7s} \"{r['pattern'][:55]}\"")
